[package]
name = "md0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "md0"
crate-type = ["cdylib"]

[dependencies]
html-escape = "0.2.13"
lazy_static = "1.5.0"
pyo3 = "0.22.0"
regex = "1.11.1"
